### ISSUE TITLE
Flexform configuration missing

### ISSUE THREAD

**Issue by sascha-egerer** [mia3/crossmedia_fourallportal#2]
A FAL driver is registered but the referenced flexform configuration (`fourallportal/Configuration/FlexForm/MamDriver.xml`) does not exist. Ends up in a Fatal Error

**Comment by NamelessCoder** [comment]
Hi Sascha,

As far as I am informed, the FAL driver must no longer be used. I don't know if the intention is to remove this code at some point but I half assume it is. In any case: if you want to use the new features you must not configure a FAL driver, as the new features only work by cloning files to the local file system and needs a local FS FAL driver as storage.

**Comment by sascha-egerer** [comment]
That was the an wer I've expected. Looks like there is much code that is not required anymore

**Comment by NamelessCoder** [comment]
I would like to do a cleanup, but this needs to be confirmed with the project plan / budget. Such a cleanup would for sure remove the FAL driver!

**Comment by NamelessCoder** [comment]
Duplicates https://github.com/mia3/crossmedia_fourallportal/issues/5, will take care of all legacy code removal there.
