### ISSUE TITLE
SQL injection at multiple places

### ISSUE THREAD

**Issue by sascha-egerer** [mia3/crossmedia_fourallportal#4]
There are multiple places where SQL injections are possible like this.
https://github.com/mia3/crossmedia_fourallportal/blob/53a0354c6fb3b71953abed0490cb7267608155d7/Classes/Task/EventHandlerState.php#L102-L106

Even if the code is not used anymore it must be removed form the project as it is still an security issue. 
You should always use the TYPO3 Query Builder to build queries and not the deprecated database methods.

Even implementations like this are not secure and may be susceptible to sql injections
https://github.com/mia3/crossmedia_fourallportal/blob/53a0354c6fb3b71953abed0490cb7267608155d7/Classes/Mapping/FalMapping.php#L127-L130

**Comment by NamelessCoder** [comment]
Closed via https://github.com/mia3/crossmedia_fourallportal/pull/9 and https://github.com/mia3/crossmedia_fourallportal/pull/7
