### ISSUE TITLE
On image synchronisation only preview images was received

### ISSUE THREAD

**Issue by kc-GitHub** [mia3/crossmedia_fourallportal#6]
On image synchronisation we received only preview images with max 256px width or height.
All files was saved as jpg files. Even other file types like pdf, psd and so on.

**Comment by NamelessCoder** [comment]
A fix for this, and another flaw that was detected while working on it, is queued in the `dynamicmodel` branch: https://github.com/mia3/crossmedia_fourallportal/commit/67a7e7852ed37d54d63cc911d26f9f42766e8b89
